kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-test-1
spec:
  # storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-test-1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: test2
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test2
    spec:
      containers:
      - name: nfs-test-1
        image: busybox
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
          - name: nfs-pvc
            mountPath: "/home"
      # restartPolicy: "Never"
      volumes:
        - name: nfs-pvc
          persistentVolumeClaim:
            claimName: nfs-test-1

# tar -cvf nfs.tar nfs
# scp -i ../master.pem nfs.tar ubuntu@172.31.42.112:/home/ubuntu/
# tar -xf nfs.tar

