apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1
  namespace: apps
  labels:
    app.kubernetes.io/name: test1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: test1
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test1
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: test1
          image: hashicorp/http-echo
          imagePullPolicy: IfNotPresent
          args:
            - -listen=:3000
            - -text=test1
          ports:
            - name: app-port
              containerPort: 3000
          resources:
            requests:
              cpu: 0.125
              memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: test1
  namespace: apps
  labels:
    app.kubernetes.io/name: test1
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: test1
  ports:
    - name: svc-port
      port: 80
      targetPort: app-port
      protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apps-ingress
  namespace: apps
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test1
                port:
                  name: svc-port
