
all:
  hosts:
    master:
      ansible_host: 3.1.102.195
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ../../aws_keys/master.pem
    worker:
      ansible_host: 54.169.169.207
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ../../aws_keys/worker.pem
  children:
    kube_control_plane:
      hosts:
        master:
    etcd:
      hosts:
        master:
    kube_node:
      hosts:
        worker:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
