
all:
  hosts:
    master:
      ansible_host: 54.169.234.245
      ansible_user: ubuntu
      ansible_ssh_private_key_file: aws_keys/master.pem
    worker:
      ansible_host: 52.221.210.248
      ansible_user: ubuntu
      ansible_ssh_private_key_file: aws_keys/worker.pem
  children:
    kube_control_plane:
      hosts:
        master:
    etcd:
      hosts:
        master:
    kube_node:
      hosts:
        worker:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
# etcdctl --endpoints=https://172.31.31.18:2379 --cacert=/etc/ssl/etcd/ssl/ca.pem --cert=/etc/ssl/etcd/ssl/node-master.pem --key=/etc/ssl/etcd/ssl/node-master-key.pem snapshot save snapshot.db
