
all:
  hosts:
    master:
      ansible_host: 54.151.200.98
      ansible_user: ubuntu
      ansible_ssh_private_key_file: aws_keys/master.pem
    master1:
      ansible_host: 52.77.255.151
      ansible_user: ubuntu
      ansible_ssh_private_key_file: aws_keys/master.pem
    worker:
      ansible_host: 18.141.160.148
      ansible_user: ubuntu
      ansible_ssh_private_key_file: aws_keys/worker.pem
  children:
    kube_control_plane:
      hosts:
        master:
        master1:
    etcd:
      hosts:
        master:
    kube_node:
      hosts:
        worker:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
